### ISSUE TITLE
0.4.12-dev Lua out of mememory on map generation

### ISSUE THREAD

**Issue by FreeLikeGNU** [paramat/riverdev#1]
Subgame crashed with 
  ERROR[main]: ServerError: Lua: OOM error in environment_OnGenerated(): not enough memory

Minetest 0.4.12-dev-bcf47bc
Using Irrlicht 1.8.1
Build info: VER=0.4.12-dev-bcf47bc BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."

**Comment by paramat** [comment]
This mod uses huge amounts of memory due to the excessive use of lua 3D noise. Memory use by lua noise has been reduced recently by hmmmm, i will implement the improvements in my mods once 0.4.13 is released and the new code available in a stable release.

**Comment by paramat** [comment]
It might be something to do with luajit not being able to cope with large memory usage, see IRC logs:
http://irc.minetest.ru/minetest-dev/2015-08-07#i_4354370
http://irc.minetest.ru/minetest-dev/2015-08-07#i_4354411
So you could try disabling luajit.
How much RAM do you have? Riverdev uses up to 2GB to process the 3D noise, plus there might be the large build up of mesh data caused by exploring the world (up to 0.5GB per minute if flying over a world).

**Comment by FreeLikeGNU** [comment]
My server has only 2 GB ram (and hardly any swap) hosted on a linode VPS.

**Comment by paramat** [comment]
Aha that's probably why. In a few weeks i will update riverdev and watershed etc to use less memory, then you could try again.
